### ISSUE TITLE
Per agent statistics

### ISSUE THREAD

**Issue by msimonin** [kgiusti/ombt#14]
Currently the controller aggregates all the results from all the agents.

This would be nice if the statistics could be reported by agent. Ideally this could be dumped in a file in json format (one json per agent's statistics).
Implementation-wise I guess that a `json.dumps` of the `Stats` instance each time it is received by the controller is enough.

I think we can wait for @avankemp to PR this since I know he wrote some code for that :)

**Comment by avankemp** [comment]
Indeed I've added a `--output` option to the controller to get the results per agent dumped in a given file. Just have to check few things and I will PR it :)

**Comment by msimonin** [comment]
Currently (v2.2.1) controller can output statistics for every single agent in the experiment.
For now only latency stats is dumped. I think we should dump the whole `TestResult` for each agent since calling [`to_dict`](https://github.com/kgiusti/ombt/blob/d0b789a382cba2f921a157b8b50373a44fcf2640/ombt2#L225) on a test result would be easily serializable into a json string.
