### ISSUE TITLE
Make delay between client completion and server results poll configurable

### ISSUE THREAD

**Issue by kgiusti** [kgiusti/ombt#8]
The delay between RPC cast clients/Notifiers reporting test complete and the controller's first poll of the servers should be configurable.

Since RPC cast and Notifiers do not block for an ack from the servers it is possible that all clients will consider the test complete *before* the messages actually arrive at the servers.  If the controller issues a poll for results from the servers before any messages have arrived then all servers will report zero and the controller will consider the test complete.

When a test is run with a small number of casts/notifications and the message bus has a high propagation delay it is possible that the test will fail in the above scenario.

**Comment by msimonin** [comment]
For the case where we run `ombt` in a very controlled way (e.g fixed number of clients/servers and messages sent), the user can know in advance how many messages are expected to be received on the servers side. 
The test [[1]](https://github.com/kgiusti/ombt/blob/3d74b8d28bef55b09035bf0676ad119e8726dd9a/ombt2#L920) could be modified to something like : 

In the case we expect a certain number of messages to arrive : 
```
done = (polling_server_time >= max_polling_server_time or messages_count >= expected_messages_count)
```
or (if the total number of messages isn't set)
```
done = (seen == 0)
```

**Comment by kgiusti** [comment]
You've got a good point there!  I'll be traveling the next week but I can work on that change when I get back Or feel free to submit a pull request if you've got the time & desire to try it yourself.

**Comment by kgiusti** [comment]
Pull request #10 includes that message count check now.  Let me know what you think.

**Comment by msimonin** [comment]
That looks good. We'll start using the feature.
Thanks !
